version: '3.8'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    restart: always
    command:
      uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.15
    restart: always
    volumes:
      - pgadmin_data:/var/lib/pgadmin:rw
    ports:
      - "15432:15432"
    env_file:
      - ./backend/.env
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 0
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 0
      # Default user for desktop mode (SERVER_MODE = False)
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      # Default password for desktop mode (SERVER_MODE = False)
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 15432

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/frontend/
      - /frontend/node_modules
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  pgadmin_data:
